admin_core_common_header:
    path:     /header
    defaults: { _controller: CoreCommonBundle:AdminLayout:header }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
    methods: [GET]

admin_core_common_sidebar:
    path:     /sidebar
    defaults: { _controller: CoreCommonBundle:AdminLayout:sidebar }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
    methods: [GET]