imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator: { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  null #session.handler.pdo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'form/fields.html.twig'
    globals:
        language_requirements: %language_requirements%
        emails:
            sender: %emails.sender%,
            support: %emails.support%
        websocket_url: %websocket_url%    
        translation_locales: %language_country_pairs%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FOSUserBundle, CoreUserBundle, CoreMediaBundle, CoreMessageBundle, CoreCommonBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Core\UserBundle\Entity\User
    from_email:
        address: %emails.sender%
        sender_name: Tarskereso
    registration:
        form:
            type: Core\UserBundle\Form\Type\RegistrationType
        confirmation:
            enabled:    true
            template: CoreUserBundle:Registration:emailVerification.html.twig
    service:
        mailer: core_common.mailer
        user_manager: core_user.user_manager
    resetting:
        token_ttl: 86400
        email:
            template:   CoreUserBundle:Resetting:emailResetting.html.twig

vich_uploader:
    db_driver: orm
    storage:   file_system
    mappings:
        core_media_image:
            uri_prefix:         /
            upload_destination: %kernel.root_dir%/../media
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   true
            namer:              core_media.image_upload_uniq_hash_namer
            directory_namer:    core_media.image_upload_user_id_hash_directory_namer

igorw_file_serve:
    base_dir: %kernel.root_dir%/../media

fos_rest:
    format_listener:
        rules:
            - { path: '^/([a-z][a-z]|)/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/([a-z][a-z]|)/resetting', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    view:
        formats:
            html: true
            json: true
            rss: false
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        empty_content: 204
    disable_csrf_role: ROLE_APP
    routing_loader:
        default_format: html
        include_format: false

jms_serializer:
    handlers:
        datetime:
            default_format: "c" # ISO8601
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
    property_naming:
        separator: _
        lower_case: true

bazinga_js_translation:
    locale_fallback: en

liip_imagine:
    resolvers:
       default_image_previews:
          web_path:
            web_root: %kernel.root_dir%/../web
            cache_prefix: images/image_previews
    loaders:
        default_images:
            filesystem:
                data_root: %kernel.root_dir%/../web/bundles/coremedia/images
        protected_images:
            filesystem:
                data_root: %kernel.root_dir%/../media
    filter_sets:
        default_image_preview:
            data_loader: default_images
            cache: default_image_cache
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
        image_preview:
            data_loader: protected_images
            cache: image_preview_cache
            filters:
                thumbnail: { size: [150, 150], mode: outbound }

# Hashids configuration
cayetanosoriano_hashids:
    salt: "jiuz6rgZR" #optional
    min_hash_length: 10 #optional

fos_js_routing:
    routes_to_expose: [ fos_user_security_logout ]
    
facile_crossbar_http_publisher:
    connections:
        crossbar_publisher:
            path: tarskerpublish                #default: publish
            auth_key: tarsker                   #default: null
            auth_secret: 22<S3/D4$}8hSTWarz64   #default: null      
            protocol: http                      #default: http
            host: 127.0.0.1                     #default: 127.0.0.1 
            port: 8080                          #default: 8080
            ssl_ignore: true
